[package]
name = "library-patcher"
version = "0.3.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
fs-err = "3.1.1"
glob = "0.3.2"
goblin = "0.10.0"
